### ISSUE TITLE
Multithread run mode

### ISSUE THREAD

**Issue by cail** [Aquantia/iperf#9]
Iperf now runs all streams in a single main thread.

This makes it inefficient when multicore processing is required and data is actually coming in with RSS on different physical cores.

Especially this is visible on UDP small packet tests.

Suggest to investigate how we can split streams to be fetched by different pthreads, possibly with custom affinity.

**Comment by LikHait** [comment]
`--multithread`
> TODO: add -lpthread to Makefile

Added for gcc

**Comment by LikHait** [comment]
`--thread-affinity `
automatic set thread affinity, use only with --multithread

**Comment by LikHait** [comment]
> Server receive has 100% CPU load all time, but client hasn't (reverse mode).

Server sockets is nonblocking if !stream->sender

**Comment by cail** [comment]
merged
